//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingITSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavilions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pavilions()
        {
            this.PavilionsLease = new HashSet<PavilionsLease>();
        }
    
        public string PavilionId { get; set; }
        public decimal Area { get; set; }
        public int LevelNumber { get; set; }
        public decimal ValueAddedFactor { get; set; }
        public decimal SquareMeterCost { get; set; }
        public int MallId { get; set; }
    
        public virtual Malls Malls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PavilionsLease> PavilionsLease { get; set; }
    }
}
