//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingITSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PavilionsLease
    {
        public int LeaseId { get; set; }
        public string PavilionId { get; set; }
        public Nullable<System.DateTime> LeaseStart { get; set; }
        public Nullable<System.DateTime> LeaseEnd { get; set; }
        public int PavilionStatusId { get; set; }
    
        public virtual Pavilions Pavilions { get; set; }
        public virtual PavilionStatuses PavilionStatuses { get; set; }
    }
}
